title: Butterfly garden
hero_image: images/banner.png
description: butterfly-garden description
version: 4
listed: false
copyedit: false
last_tested: "2020-06-03"
steps:
  - title: Introduction
  - title: Add a flying butterfly
  - title: Flying at an angle
  - title: "Challenge: add a butterfly"
  - title: Round and round
  - title: "Challenge: Add to your garden"
  - title: What next?
