---
title: Butterfly garden
hero_image: images/butterfly-banner.png
description: Sit back, relax, and watch the patterns the butterflies make as they
  fly
pdf: resources/rpi-butterfly-garden.pdf
version: 4
listed: true
copyedit: true
last_tested: '2020-09-01'
steps:
- title: Introduction
- title: Add a flying butterfly
- title: Fly at an angle
  completion:
  - engaged
- title: Make a small butterfly
- title: Round and round
  completion:
  - internal
- title: Add more
- title: What can you do now?
  completion:
  - external
