title: Butterfly garden
hero_image: images/butterfly-banner.png
description: Sit back, relax, and watch the patterns the butterflies make as they fly
version: 4
listed: false
copyedit: false
last_tested: "2020-06-03"
steps:
  - title: Introduction
  - title: Add a flying butterfly
  - title: Flying at an angle
  - title: Add a small butterfly
  - title: Round and round
  - title: "Challenge: add to your garden"
  - title: What next?
