title: Butterfly garden
hero_image: images/butterfly-banner.png
description: Sit back, relax, and watch the patterns the butterflies make as they fly
version: 4
listed: true
copyedit: true
last_tested: "2020-09-01"
steps:
  - title: Introduction
  - title: Add a flying butterfly
  - title: Fly at an angle
  - title: Make a small butterfly
  - title: Round and round
  - title: Add more
  - title: What next?
